services:
  spring:
    image: 'ftacurip/spring-person:0.13'
    container_name: spring
    expose:
      - "8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://basesalesiana.postgres.database.azure.com:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Salesiana1
  angular:
    image: 'devcorpecu/crud-angular:0.3'
    container_name: docker-angular
    ports:
      - "80:80"
    depends_on:
      - spring